environment:
    matrix:
        - TOXENV: py27
        - TOXENV: py36

install:
    - "SET PATH=C:\\Python36;C:\\Python36\\Scripts;%PATH%"
    - pip install tox virtualenv --upgrade

# Not a C# project
build: false

test_script: tox

cache:
  - '%LOCALAPPDATA%\pip\cache'
  - '%USERPROFILE%\.cache\pre-commit'
